version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./../:/var/www/app
    links:
      - app
  app:
    build: ./php
    restart: always
    volumes:
      - ./../:/var/www/app
    working_dir: /var/www/app